# Generated by Django 5.0.6 on 2024-06-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='local_images/')),
            ],
        ),
    ]
