# Generated by Django 5.0.6 on 2024-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0002_inter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
