# Generated by Django 5.0.6 on 2024-06-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('additional_image1', models.ImageField(upload_to='images/')),
                ('additional_image2', models.ImageField(upload_to='images/')),
                ('additional_image3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
