# Generated by Django 5.0.6 on 2024-06-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0004_restaurant'),
    ]

    operations = [
    ]
