# Generated by Django 5.0.6 on 2024-06-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0005_auto_20240623_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='name',
            field=models.CharField(default='1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agthiaApp.local'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='local_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='local_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='local_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image1',
            field=models.ImageField(upload_to='local_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image2',
            field=models.ImageField(upload_to='local_images/'),
        ),
    ]
