# Generated by Django 5.0.6 on 2024-06-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0006_local_name_restaurant_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='brand_type',
            field=models.CharField(choices=[('LOCAL', 'Local Brands'), ('INTERNATIONAL', 'International Brands')], default='LOCAL', max_length=20),
        ),
    ]
