# Generated by Django 5.0.6 on 2024-06-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthiaApp', '0007_restaurant_brand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter',
            name='name',
            field=models.CharField(default='1', max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_type', models.CharField(choices=[('LOCAL', 'Local Brands'), ('INTERNATIONAL', 'International Brands')], default='LOCAL', max_length=20)),
                ('image1', models.ImageField(upload_to='local_images/')),
                ('image2', models.ImageField(upload_to='local_images/')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to='local_images/')),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to='local_images/')),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to='local_images/')),
                ('inter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agthiaApp.inter')),
            ],
        ),
    ]
